# Generated by Django 5.0.6 on 2024-06-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='selfstudy.chapter', verbose_name='раздел'),
            preserve_default=False,
        ),
    ]
